parameters: {}
environment: {}
packages:
    - name: crm
      shared: false
      environment: {}
      parameters: {}
      annotations: {}
      functions:
        - name: contactform
          binary: false
          main: ""
          runtime: nodejs:default
          web: true
          parameters: {}
          environment: {}
          annotations: {}
          limits: {}
